CREATE TABLE AUDIT_TABLE (
    AUDIT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ENTITY_TYPE VARCHAR2(10) NOT NULL, 
    ENTITY_ID NUMBER NOT NULL,
    ENTITY_NAME VARCHAR2(100) NOT NULL,
    GROUP_ID NUMBER,
    С_VAL NUMBER,
    ACTION_TYPE VARCHAR2(10) NOT NULL,
    ACTION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    OLD_ENTITY_NAME VARCHAR2(100),
    OLD_GROUP_ID NUMBER,
    OLD_C_VAL NUMBER 
);