CREATE TABLE Groups (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    C_VAL NUMBER
);

CREATE TABLE Students (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    GROUP_ID NUMBER
);